name: infrasim
channels:
  - gurobi
  - defaults
dependencies:
  - attrs=20.2.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.7.22
  - cairo=1.14.12
  - certifi=2020.6.20
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.5.0
  - curl=7.67.0
  - cycler=0.10.0
  - decorator=4.4.2
  - expat=2.2.9
  - fiona=1.8.13.post1
  - fontconfig=2.13.0
  - freetype=2.10.2
  - freexl=1.0.5
  - gdal=3.0.2
  - geopandas=0.8.1
  - geos=3.8.0
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.63.1
  - gurobi=9.0.3
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.4
  - jpeg=9b
  - json-c=0.13.1
  - kealib=1.4.7
  - kiwisolver=1.2.0
  - krb5=1.16.4
  - lcms2=2.11
  - libboost=1.67.0
  - libcurl=7.67.0
  - libcxx=10.0.0
  - libdap4=3.19.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgdal=3.0.2
  - libgfortran=3.0.1
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libpq=11.2
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - lz4-c=1.8.1.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - munch=2.5.0
  - ncurses=6.2
  - networkx=2.5
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1h
  - pandas=1.1.1
  - pcre=8.44
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.40.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - postgresql=11.2
  - proj=6.2.1
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2020.1
  - readline=7.0
  - rtree=0.9.4
  - scipy=1.5.2
  - seaborn=0.11.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - sqlite=3.33.0
  - tbb=2018.0.5
  - tiledb=1.6.3
  - tk=8.6.10
  - tornado=6.0.4
  - tqdm=4.49.0
  - wheel=0.35.1
  - xerces-c=3.2.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - salib==1.3.11
    - snkit==1.6.0
